### ISSUE TITLE
Check/Uncheck all

### ISSUE THREAD

**Issue by fprochazka** [adammck/gh-news-feed-filters#1]
It's annoing to click on all checkboxes one by one in the alerts select.

**Comment by adammck** [comment]
Yeah, it's pretty annoying. It needs select all/none links at the bottom of the list. I'll fix it when I get a chance, but pull requests are always welcome.

**Comment by fprochazka** [comment]
I would made it by myself but I'm no friend with coffee script :-(

**Comment by fprochazka** [comment]
Thank you!
