### ISSUE TITLE
Uncheck all alerts when repository is unwatched

### ISSUE THREAD

**Issue by fprochazka** [adammck/gh-news-feed-filters#2]
I've unwatched few repositories and they still appear in my news feed. When I uncheck all of the checkboxes in Alerts select, they disappear completely.

**Comment by adammck** [comment]
GitHub's usual behavior when one unwatches a repo is to stop adding new events to the feed, but leave the old ones there. I don't think this extension should change that.

**Comment by fprochazka** [comment]
Ok, I didn't know that. Still think it would be better to filter them off.
